(java) 1153: Finish CI/CD setup (#1225)

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -38,12 +38,30 @@ jobs:
         if: matrix.language != 'java'
         uses: github/codeql-action/autobuild@v3
 
+      - name: Import Java GPG key
+        #This step will be removed from here once we add build profile for java. Let's keep it here for now :)
+        run: |
+          set +e 
+          echo "$GPG_PRIVATE_KEY" | tr -d '\r' | sed '1s/^\xEF\xBB\xBF//' | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > clean_gpg_key.asc
+          gpg --batch --import clean_gpg_key.asc
+          GPG_EXIT_CODE=$?
+
+          set -e
+          if [ $GPG_EXIT_CODE -ge 3 ]; then
+            echo "GPG import failed with code $GPG_EXIT_CODE"
+            exit $GPG_EXIT_CODE
+          else
+            echo "GPG key imported successfully"
+          fi
+        env:
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+
       - name: Build for Java and Kotlin
         if: matrix.language == 'java'
         run: |
-          mvn clean install -f packages/java/metrics-core/pom.xml
-          mvn clean install -f packages/java/metrics-spring/pom.xml
-          mvn clean install -f packages/java/metrics-spring2/pom.xml
+          mvn clean install -f packages/java/metrics-core/pom.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
+          mvn clean install -f packages/java/metrics-spring/pom.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
+          mvn clean install -f packages/java/metrics-spring2/pom.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
 
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3
diff --git a/.github/workflows/java.yaml b/.github/workflows/java.yaml
--- a/.github/workflows/java.yaml
+++ b/.github/workflows/java.yaml
@@ -6,6 +6,7 @@ on:
       - main
     paths:
       - 'packages/java/**'
+      - '.github/**'
 
 jobs:
   build-and-deploy-core:
@@ -23,20 +24,33 @@ jobs:
           java-version: '17'
 
       - name: Configure Maven settings.xml
-        run: echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml
-
-      - name: Build & Test metrics-core
-        working-directory: packages/java
-        run: mvn clean verify
-
-      - name: Import GPG Key
         run: |
-          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
+          mkdir -p ~/.m2
+          echo "${{ secrets.MAVEN_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml
+
+      - name: Import GPG key
+        run: |
+          set +e 
+          echo "$GPG_PRIVATE_KEY" | tr -d '\r' | sed '1s/^\xEF\xBB\xBF//' | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > clean_gpg_key.asc
+          gpg --batch --import clean_gpg_key.asc
+          GPG_EXIT_CODE=$?
+
+          set -e
+          if [ $GPG_EXIT_CODE -ge 3 ]; then
+            echo "GPG import failed with code $GPG_EXIT_CODE"
+            exit $GPG_EXIT_CODE
+          else
+            echo "GPG key imported successfully"
+          fi
         env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
 
+      - name: Build & Test metrics-core
+        working-directory: packages/java/metrics-core
+        run: mvn clean verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
+
       - name: Deploy metrics-core
-        working-directory: packages/java
+        working-directory: packages/java/metrics-core
         run: mvn deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
 
   build-and-deploy-for-spring3:
@@ -55,17 +69,34 @@ jobs:
           java-version: '17'
 
       - name: Configure Maven settings.xml
-        run: echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml
-
-      - name: Build & Test metrics-spring
-        working-directory: packages/java/metrics-spring
-        run: mvn clean verify
+        run: |
+          mkdir -p ~/.m2
+          echo "${{ secrets.MAVEN_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml
 
       - name: Import GPG Key
         run: |
-          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
+          set +e 
+          echo "$GPG_PRIVATE_KEY" | tr -d '\r' | sed '1s/^\xEF\xBB\xBF//' | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > clean_gpg_key.asc
+          gpg --batch --import clean_gpg_key.asc
+          GPG_EXIT_CODE=$?
+
+          set -e
+          if [ $GPG_EXIT_CODE -ge 3 ]; then
+            echo "GPG import failed with code $GPG_EXIT_CODE"
+            exit $GPG_EXIT_CODE
+          else
+            echo "GPG key imported successfully"
+          fi
         env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+
+      - name: Build metrics-core for dependency
+        working-directory: packages/java/metrics-core
+        run: mvn clean install -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
+
+      - name: Build & Test metrics-spring
+        working-directory: packages/java/metrics-spring
+        run: mvn clean verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
 
       - name: Deploy metrics-spring
         working-directory: packages/java/metrics-spring
@@ -87,19 +118,34 @@ jobs:
           java-version: '17'
 
       - name: Configure Maven settings.xml
-        run: echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml
-
-      - name: Build & Test metrics-spring2
-        working-directory: packages/java/metrics-spring2
-        run: mvn clean verify
+        run: |
+          mkdir -p ~/.m2
+          echo "${{ secrets.MAVEN_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml
 
       - name: Import GPG Key
         run: |
-          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
+          set +e 
+          echo "$GPG_PRIVATE_KEY" | tr -d '\r' | sed '1s/^\xEF\xBB\xBF//' | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > clean_gpg_key.asc
+          gpg --batch --import clean_gpg_key.asc          GPG_EXIT_CODE=$?
+
+          set -e
+          if [ $GPG_EXIT_CODE -ge 3 ]; then
+            echo "GPG import failed with code $GPG_EXIT_CODE"
+            exit $GPG_EXIT_CODE
+          else
+            echo "GPG key imported successfully"
+          fi
         env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+
+      - name: Build metrics-core for dependency
+        working-directory: packages/java/metrics-core
+        run: mvn clean install -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
+
+      - name: Build & Test metrics-spring2
+        working-directory: packages/java/metrics-spring2
+        run: mvn clean verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
 
       - name: Deploy metrics-spring2
         working-directory: packages/java/metrics-spring2
         run: mvn deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
-
