Test: trying to fix 'invalid armor header:' - suppress warnings, cleaning more junk chars

diff --git a/.github/workflows/java.yaml b/.github/workflows/java.yaml
--- a/.github/workflows/java.yaml
+++ b/.github/workflows/java.yaml
@@ -33,20 +33,32 @@ jobs:
         working-directory: packages/java/metrics-core
         run: mvn clean verify
 
-#      - name: Import GPG Key
-#        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
-#        env:
-#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
-
       - name: Clean and import GPG key
-        run: |
-          echo "$GPG_PRIVATE_KEY" | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > clean_gpg_key.asc
+        run:
+          set +e
           
+          echo "$GPG_PRIVATE_KEY" \
+          | tr -d '\r' \
+          | sed '1s/^\xEF\xBB\xBF//' \
+          | sed '/^\s*$/d' \
+          | sed 's/^[ \t]*//;s/[ \t]*$//' \
+          > clean_gpg_key.asc
+
           echo "===== START OF KEY ====="
           cat clean_gpg_key.asc
           echo "===== END OF KEY ====="
-          
+    
           gpg --batch --import clean_gpg_key.asc
+          GPG_EXIT_CODE=$?
+  
+          set -e
+  
+          if [ $GPG_EXIT_CODE -ne 0 ]; then
+            echo "GPG import failed with code $GPG_EXIT_CODE"
+            exit $GPG_EXIT_CODE
+          else
+            echo "GPG key imported successfully"
+          fi
         env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
 
